### ISSUE TITLE
Implement ADR-070: unordered transactions

### ISSUE THREAD

**Issue by larry0x** [left-curve/grug#10]
https://github.com/cosmos/cosmos-sdk/blob/main/docs/architecture/adr-070-unordered-transactions.md

**Comment by larry0x** [comment]
Quick thoughts:

There're two ways we can implement this; I'm not sure which is more preferred:

1. Add a new `data` field to `Tx`:

  ```rust
  struct Tx {
      pub sender: Addr,
      pub messages: Vec<Messages>,
      pub credential: Json,
      pub data: Option<Json>, // new!
      pub gas_limit: u64,
  }
  ```

  This field can be any auxiliary data. E.g. 1) informing the account whether the tx is to be ordered or unordered; 2) informing the taxman about the sender's preference for gas fee payment (if taxman supports multiple fee tokens, this can specify which token to use).

2. Modify `grug_account::Credential` into an enum:

  ```rust
  enum Credential {
      Ordered { signature: Binary },
      Unordered { signature: Binary, expiry: Timestamp },
  }
  ```

  If ordered, the `Binary` is a signature (of which the sign bytes include the sequence). If unordered, the sign bytes do not include the sequence, and there's an additional `expiry` parameter specifying when the txhash can be purged from the storage dictionary (see ADR-070 for details).

---

Either way, we should add `txhash` to `Context`, so that the account contract doesn't need to serialize and hash the transaction.

Inside the contract storage, there should be an `IndexedSet` that stores the txhashes, indexed by the expiry time.

**Comment by Rhaki** [comment]
Also grug account needs some adjustment. If thx tx is unorder, the `sequence` has not be used for generating the sign. I would prefer the solution n°2, modifying credential

**Comment by Rhaki** [comment]
In case we don't insert the `txhash` to `Context`, we have to adapt account the remove sequence on `make_sign_bytes`. I would prefer solution #2, keeping the `credentials` info separate from any other fields (the `taxman` won't care about the credentials part). As expiration do we want to use a `Timestamp`, a block height or maybe give the possibility to choose?

**Comment by Rhaki** [comment]
When the account verifies the signature, the `hash` is created differently than the `App` does during `do_finalize_block_raw` (where the entire `tx` is hashed). The `sequence` is also inserted during hashing by the account for ordered tx, since the `App` has no access unless it explicitly asks the account what the next sequence is. In unordered ones, the sequence must not be inserted in make_sign_bytes.

I would prefer solution n°2, keeping the credentials info separate from any other fields (the taxman won't care about the credentials part). As expiration do we want to use a Timestamp, a block height or maybe give the possibility to choose?

**Comment by larry0x** [comment]
Since contracts in this repo are just for testing purpose, and not for production use, I suggest we keep them simple and don't implement this here.

We can implement this in a separate, production contracts repo.
