### ISSUE TITLE
Allow an account to send multiple txs in a block

### ISSUE THREAD

**Issue by larry0x** [left-curve/grug#82]
In the current design, a sender can only have one transaction (tx) per block. This is due to how account sequence number works.

Suppose the account expects the next tx to have sequence number N, and there's already a tx in the mempool with sequence N.

- If the sender broadcasts another tx with sequence (N+1), then `CheckTx` would fail, because the account expects N.

- If the sender broadcasts another tx with sequence N, then `CheckTx` would succeed, but `FinalizeBlock` would fail, because after executing the first tx, the account would expect (N+1).

This problem can be fixed in one of three ways:

## Method 1. Have the account support unordered txs

See [ADR-070](https://github.com/cosmos/cosmos-sdk/blob/2e0884564fdbe11e505d9cf48be618b917f42cf7/docs/architecture/adr-070-unordered-transactions.md?plain=1#L4).

## Method 2. Skip sequence check during CheckTx

This involves modifying `AuthCtx` as follows:

```diff
struct AuthCtx {
-   simulate: bool,
+   mode: AuthMode,
    // other fields...
}

enum AuthMode {
    Simulate,
    Check,
    Finalize,
}
```

## Method 3. The app to maintain a volatile state for CheckTx

```diff
struct App<DB, VM>
where
    DB: Db,
    Vm: Vm,
{
    db: DB
    vm: VM,
+   check_tx_state: Shared<Buffer<Self::DB::StateStorage>>,
    query_gas_limit: u64,
}
```

The state change effected by `CheckTx` is kept in `App::check_tx_state`. This way, after the tx with sequence N is accepted into the mempool, the updated sequence is remembered, so a subsequence tx with sequence N+1 would succeed in `CheckTx`.

This is the [same approach used by Cosmos SDK](https://github.com/cosmos/cosmos-sdk/blob/v0.50.8/baseapp/baseapp.go#L99-L118).

**Comment by Rhaki** [comment]
`Method 1` can be implemented as an alternative, not as a solution to the problem. Allowing to have multiple tx in the `mempool` signed with the sequence should be independent from `ADR-070`, the latter in fact allows even in case of reordering of the tx in the proposal block to not make them fail.

`Method 2` is very clean. It allows to manage the validity of the tx based on the variant. However, the sequence would still be verified in the case of `check_tx` since the signature of the tx is still generated with the sequence, so to verify its validity it must be inserted. I propose in the `credential` field of `Tx` of type `serde::Value`, to use a `Struct` for the account that contains the sequence and the signature (currently the `credential` field is the signature itself). This allows in the `check_tx` to verify the signature with the specified sequence instead of using the one saved in the contract + 1. It is also advisable in the `check_tx` to verify that the sequence passed is greater than the one saved to prevent spam once a tx is written to a block.

I don't think that in our case `method 3` is necessary, it would unnecessarily complicate a process that we can achieve with `method 2` in a much more streamlined way

**Comment by larry0x** [comment]
@Rhaki The problem with method 2 is, say you broadcast two txs, first with sequence N and second with sequence N+1.

However, they arrive at the node in the reverse order (because internet latency, packet loss and so on).

They are both accepted into mempool because sequence check is skipped.

Then in the proposed block, the N+1 one comes first and N one comes second (Tendermint mempool is first-in-first-out). The N+1 one would fail.

**Comment by larry0x** [comment]
Completed by #85
